export const PaymentCardLogos = {
  alipay: '/images/cc_logos/alipay.svg',
  code: '/images/cc_logos/code.svg',
  elo: '/images/cc_logos/elo.svg',
  visa: '/images/cc_logos/visa.svg',
  paypal: '/images/cc_logos/paypal.svg',
  mastercard: '/images/cc_logos/mastercard.svg',
  generic: '/images/cc_logos/generic.svg',
  hiper: '/images/cc_logos/hiper.svg',
  hipercard: '/images/cc_logos/hipercard.svg',
  maestro: '/images/cc_logos/maestro.svg',
  mir: '/images/cc_logos/mir.svg',
  amex: '/images/cc_logos/amex.svg',
  discover: '/images/cc_logos/discover.svg',
  diners: '/images/cc_logos/diners.svg',
  jcb: '/images/cc_logos/jcb.svg',
  unionpay: '/images/cc_logos/unionpay.svg',
} as const;

export const CARD_BRANDS = {
  ALIPAY: 'alipay',
  CODE: 'c[ode',
  ELO: 'elo',
  VISA: 'visa',
  PAYPAL: 'paypal',
  MASTERCARD: 'mastercard',
  GENERIC: 'generic',
  HIPER: 'hiper',
  HIPERCARD: 'hipercard',
  MAESTRO: 'maestro',
  MIR: 'mir',
  AMEX: 'amex',
  DISCOVER: 'discover',
  DINERS: 'diners',
  JCB: 'jcb',
  UNIONPAY: 'unionpay',
} as const;

export const CARD_BRAND_LOGOS = {
  [CARD_BRANDS.ALIPAY]: PaymentCardLogos.alipay,
  [CARD_BRANDS.CODE]: PaymentCardLogos.code,
  [CARD_BRANDS.ELO]: PaymentCardLogos.elo,
  [CARD_BRANDS.VISA]: PaymentCardLogos.visa,
  [CARD_BRANDS.PAYPAL]: PaymentCardLogos.paypal,
  [CARD_BRANDS.MASTERCARD]: PaymentCardLogos.mastercard,
  [CARD_BRANDS.GENERIC]: PaymentCardLogos.generic,
  [CARD_BRANDS.HIPER]: PaymentCardLogos.hiper,
  [CARD_BRANDS.HIPERCARD]: PaymentCardLogos.hipercard,
  [CARD_BRANDS.MAESTRO]: PaymentCardLogos.maestro,
  [CARD_BRANDS.MIR]: PaymentCardLogos.mir,
  [CARD_BRANDS.AMEX]: PaymentCardLogos.amex,
  [CARD_BRANDS.DISCOVER]: PaymentCardLogos.discover,
  [CARD_BRANDS.DINERS]: PaymentCardLogos.diners,
  [CARD_BRANDS.JCB]: PaymentCardLogos.jcb,
  [CARD_BRANDS.UNIONPAY]: PaymentCardLogos.unionpay,
} as const;
